const essentialsList = [
    "salt",
    "pepper",
    "white wine vinegar",
    "rice wine", 
    "rice wine vinegar", 
    "balsamic vinegar",
    "plain flour",
    "soy sauce",
    "balsamic",
    "honey",
    "milk",
    "eggs",
    "butter",
    "salted butter",
    "sugar",
    "olive oil",
    "garlic",
    "onion",
    "black pepper",
    "sea salt",
    "kosher salt",
    "dry white wine",
    "sweet white wine",
    "oliver oil",
    "extra virgin olive oil",
    "virgin olive oil",
    "sunflower oil",
    "sesame oil",
    "oil",
    'extra-virgin olive oil',
    'vegetable oil',
    'unsalted butter',
    'white onion',
    'red onion',
    'water',
    'filtered water',
    'white pepper',
    
]

module.exports = essentialsList