const examplePantry = [
    "chicken breast",
    "ground beef",
    "pasta",
    "rice",
    "canned tomatoes",
    "canned beans",
    "broth",
    "onions",
    "garlic",
    "carrots",
    "potatoes",
    "bell peppers",
    "mushrooms",
    "zucchini",
    "spinach",
    "frozen peas",
    "frozen corn",
    "canned tuna",
    "canned salmon",
    "bread crumbs",
    "parmesan cheese",
    "cheddar cheese",
    "mozzarella cheese",
    "cream cheese",
    "yogurt",
    "sour cream",
    "mayonnaise",
    "mustard",
    "ketchup",
    "salsa",
    "barbecue sauce",
    "pasta sauce",
    "coconut milk",
    "canned chickpeas",
    "canned lentils",
    "cornmeal",
    "quinoa",
    "oats",
    "tortillas",
    "pita bread",
    "soy milk",
    "almond milk",
    "tomato paste",
    "baking powder",
    "baking soda",
    "cocoa powder",
    "cinnamon",
    "vanilla extract",
    "peanut butter",
    "jam",
    "hummus",
    "olives",
    "capers",
    "pickles",
    "sriracha",
    "hot sauce",
    "soy milk",
    "tofu",
    "seitan",
    "tempeh",
    "frozen berries",
    "dried cranberries",
    "raisins",
    "nuts",
    "seeds",
    "whole wheat flour",
    "cornstarch",
    "soy sauce",
    "rice vinegar",
    "apple cider vinegar",
    "cooking wine",
    "bay leaves",
    "thyme",
    "rosemary",
    "oregano",
    "basil",
    "curry powder",
    "cumin",
    "paprika",
    "turmeric",
    "ground ginger",
    "nutmeg",
    "cloves",
    "cardamom",
    "coriander",
    "red pepper flakes",
    "chili powder",
    "cayenne pepper",
    "saffron",
    "fennel seeds",
    "tahini",
    "soy sauce",
    "hoisin sauce",
    "fish sauce",
    "sesame oil",
    "olive oil",
    "canola oil",
    "vegetable oil",
    "shortening",
    "vinegar",
    "sugar",
    "brown sugar",
    "powdered sugar",
    "honey",
    "maple syrup",
    "molasses"
  ];

module.exports = examplePantry